---
title: "Data Cleaning"
format: html
editor: visual
---

# Summary

This file contains code for additional cleaning on the Washington Post's fatal shootings data available at <https://github.com/washingtonpost/data-police-shootings>.

# Setup

```{r}
#| message: false
library(tidyverse)
library(here)
```

```{r}
#| message: false
agencies <- read_csv(here("data", "fatal-police-shootings-agencies.csv"))

shootings <- read_csv(here("data", "fatal-police-shootings-data.csv"))
```

# Cleaning

```{r}
shootings_clean <- shootings %>% 
  mutate(
    # Add in threat descriptions for plotting on map
    threat_description = case_when(
      threat_type == "accident" ~ "Accident (more information needed)",
      threat_type == "shoot" ~ "The victim fired a weapon.",
      threat_type == "point" ~ "The victim pointed a weapon at another individual.",
      threat_type == "attack" ~ "The victim attacked with other weapons or physical force.",
      threat_type == "threat" ~ "The victim had some kind of weapon visible to the officers on the scene.",
      threat_type == "move" ~ "The victim was moving in a threatening way.",
      threat_type == "flee" ~ "The victim was fleeing.",
      threat_type == "undetermined" ~ "The threat type could not be determined from available evidence.",
      is.na(threat_type) ~ "Unknown",
      TRUE ~ NA
    ),
    # Update race variable with more descriptive levels
    race = case_when(
      race == "A" ~ "Asian",
      race == "B" ~ "Black",
      race == "H" ~ "Hispanic",
      race == "N" ~ "Native American",
      race == "O" ~ "Other",
      race == "W" ~ "White",
      is.na(race) ~ "Unknown",
      TRUE ~ NA
    ),
    
    involved_gun = case_when(
      # If gun is explicitly referenced, yes
      str_detect(armed_with, "gun") ~ "Yes",
      
      # If there is incomplete information, unknown
      is.na(armed_with) | armed_with %in% c("undetermined", "unknown") ~ "Unknown",
      
      # Otherwise, no
      TRUE ~ "No"
    ),
    
    involved_replica = case_when(
      
      # If replica is explicitly referenced, yes
      str_detect(armed_with, "replica") ~ "Yes",
      
      # If there is incomplete information, unknown
      is.na(armed_with) | armed_with %in% c("undetermined", "unknown") ~ "Unknown",
      
      # Otherwise, no
      TRUE ~ "No"
    ),
    
    involved_knife = case_when(
      
      # If knife is explicitly referenced, yes
      str_detect(armed_with, "knife") ~ "Yes",
      
      # If there is incomplete information, unknown
      is.na(armed_with) | armed_with %in% c("undetermined", "unknown") ~ "Unknown",
      
      # Otherwise, no
      TRUE ~ "No"
    ),
    
    unarmed = case_when(
      
      # If unarmed is explicitly referenced, yes
      str_detect(armed_with, "unarmed") ~ "Yes",
      
      # If there is incomplete information, unknown
      is.na(armed_with) | armed_with %in% c("undetermined", "unknown") ~ "Unknown",
      
      # Otherwise, no
      TRUE ~ "No"
    )
  )
```

# Output

```{r}
shootings_clean %>% 
  write_csv(here("data", "shootings_clean.csv"))
```
