---
title: "EDA"
author: "Sean Leader, Rebecca Ioffe, Ashley Ibarra"
format: html
editor: visual
---

# Summary

This file is meant to be an exploration into the different visualizations and data summaries we may want to include in our shiny app.

# Setup

```{r}
#| message: false
library(tidyverse)
library(here)
library(sf)
```

```{r}
agencies <- read_csv(here("data", "fatal-police-shootings-agencies.csv"))

shootings <- read_csv(here("data", "shootings_clean.csv"))
```

```{r}
shootings
```

```{r}
state_info <- data.frame(
  NAME = state.name,
  state = state.abb
)

full_data <- spData::us_states %>% 
  inner_join(state_info, by = "NAME") %>% 
  inner_join(shootings, by = "state")
```

```{r}
full_data
```

```{r}
geometry <- spData::us_states$geometry
```

```{r}
full_data %>%
      mutate(valid_shooting = rowSums(across(all_of(c("gun"))))) %>% 
      filter(valid_shooting >= 1) %>% 
      group_by(state) %>% 
      mutate(shoot_per_cap = n() / total_pop_15) %>% 
      ungroup() %>% 
      distinct(state, shoot_per_cap, geometry)
```

```{r}
full_data %>%
      mutate(valid_shooting = rowSums(across(all_of(c("gun"))))) %>% 
      filter(valid_shooting >= 1) %>% 
      group_by(state) %>% 
      mutate(shoot_per_cap = n() / total_pop_15) %>% 
      ungroup()
```

```{r}
full_data %>% 
  group_by(state) %>% 
  count() %>% 
  rename(num_shootings = n) %>% 
  ungroup() %>% 
  inner_join(full_data, by = "state") %>% 
  mutate(shootings_per_capita = num_shootings / total_pop_15) %>% 
  distinct(state, shootings_per_capita) %>% 
  ggplot(aes(x = shootings_per_capita * 10000)) + 
  geom_histogram()
```

```{r}
shootings %>% 
  group_by(race) %>% 
  count(armed_with) %>% 
  mutate(perc = round(n / sum(n) * 100, 1)) %>% 
  filter(perc > 10) %>% 
  mutate(perc = perc / sum(perc))
```

```{r}
shootings
```
